buffer_depth: 1
clock_period_ps: 1000
flit_injection_rate: 'true'
max_packet_size: 10
min_packet_size: 10
packet_injection_rate: 0.05
probability_of_retransmission: 1
report_buffers: 'false'
report_cycle_result: 'false'
report_flit_trace: 'false'
report_possible_routes: 'false'
report_progress: 'true'
report_routes_stats: 'false'
report_routing_table: 'false'
report_sub_routing_table: 'false'
report_topology_graph: 'false'
report_topology_graph_adjacency_matrix: 'false'
report_topology_sub_graph: 'false'
report_topology_sub_graph_adjacency_matrix: 'false'
reset_time: 1000
rnd_generator_seed: 0
routing_algorithm: SUBNETWORK
routing_table: DIJKSTRA
routing_table_id_based: 'true'
scale_with_nodes: 'false'
selection_strategy: RANDOM
simulation_time: 100000
stats_warm_up_time: 0
subnetwork: PHYSICAL
subtopology: TGEN_0
topology: CIRCULANT
topology_args:
- 4
- 4
topology_channels: 1
traffic_distribution: TRAFFIC_RANDOM
update_sequence: DEFAULT
virtual_channels: 4
